language: go

go:
  - tip

before_install:
  - go get -t -v ./...
  - sudo apt-get install redis-server; redis-server &
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
