language: go

go:
  - 1.16

before_install:
  - go get -t -v ./...
  - sudo apt-get install redis-server; redis-server &
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=atomic ./...
  - $GOPATH/bin/goveralls -service=travis-ci
